main: com.forgedfactions.randomcommandtimer.RandomTimer
name: RandomCommandTimer
version: 2.0.2
author: Darkm4tter
website: www.forgedfactions.com
permissions:
  rct.admin:
    description: Access to rct commands
    default: op
commands:
  rct:
    description: Executes a command any time in a set range.
    permission: rct.admin
    usage: /rct [command name] [start/stop/execute]
  rct reload:
      description: /rct reload - Reload the plugin
      permission: rct.admin
      usage: /rct reload