main: com.forgedfactions.randomcommandtimer.RandomTimer
name: RandomCommandTimer
version: 1.0.0
author: Darkm4tter
commands:
  rct:
    description: Executes a command any time in a set range.
    usage: /rct [command name] [start/stop] -Start or stop a running command \n/rct reload - Reloads the config