main: com.forgedfactions.randomcommandtimer.RandomTimer
name: RandomCommandTimer
version: 3.5.1
author: Darkm4tter
description: A simple plugin that executes commands on a random basis.
website: www.forgedfactions.com
permissions:
  rct.admin:
    description: Access to rct commands
    default: op
  rct.time:
    description: Access to time command
    default: op
commands:
  rct:
    description: Executes a command any time in a set range.
    permission: rct.admin
    usage: /rct [command name] [start/stop/execute/time]