main: com.forgedfactions.randomcommandtimer.RandomTimer
name: RandomCommandTimer
version: 3.1.5
author: Darkm4tter
website: www.forgedfactions.com
permissions:
  rct.admin:
    description: Access to rct commands
    default: op
commands:
  rct:
    description: Executes a command any time in a set range.
    permission: rct.admin
    usage: /rct [command name] [start/stop/execute/time]
  rct list:
        description: List all registered commands
        permission: rct.admin
        usage: /rct list
  rct reload:
      description: Reload the plugin
      permission: rct.admin
      usage: /rct reload